# Generated by Django 4.1.2 on 2022-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
