# Generated by Django 4.1.2 on 2022-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_malfunction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'await for mail man'), (2, 'in process'), (3, 'phone ready for delivery'), (4, 'phone ready mailman will arrive soon'), (5, 'order done')], null=True),
        ),
    ]
