# Generated by Django 4.1.2 on 2023-01-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_malfunction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('Malfunction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.malfunction_type')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.phone')),
            ],
        ),
    ]
