# Generated by Django 4.1.2 on 2023-01-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='phone',
            new_name='phone_device',
        ),
    ]
