# Generated by Django 4.1.2 on 2023-01-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_rename_phone_price_phone_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunction',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
