# Generated by Django 4.1.2 on 2023-01-12 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0010_handled_by_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handled_by',
            name='mail_man_OR_technician',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
