# Generated by Django 4.1.3 on 2022-12-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.PositiveIntegerField(choices=[(1, 'Mail_Man'), (2, 'Technician')], null=True),
        ),
    ]
