# Generated by Django 4.1.3 on 2022-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.PositiveIntegerField(choices=[(1, 'Mail_Man'), (2, 'Technician'), (3, 'Admin')], null=True),
        ),
    ]
